site_name: Event driven Architecture Vessel course simulator
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc-vessel-simulator
nav:
  - Introduction: index.md
  - Compendium: compendium.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences